image: docker:23.0.6

services:
  - docker:23.0.6-dind

variables:
  DOCKER_DRIVER: overlay2
  AWS_TAG_LATEST: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$AWS_IMAGE_NAME:latest
  DOCKER_HOST: tcp://docker:2375

aws:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  services:
    - docker:dind
  stage: build
  script:
    - echo "$AWS_REGION - $AWS_TAG_LATEST - $AWS_IMAGE_NAME"
    - aws ecr get-login-password --region $AWS_REGION |
      docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
    - docker pull $AWS_TAG_LATEST || true
    - docker build --cache-from $AWS_TAG_LATEST -t $AWS_TAG_LATEST .
    - docker push $AWS_TAG_LATEST
  only:
    - master
