export enum AssertionType {
  RESPONSE_TIME,
  RESPONSE_CODE,
  RESPONSE_VALUE,
  RESPONSE_JSON,
  RESPONSE_HEADER,
  SSL_CERTIFICATE_EXPIRES_IN,
}

export const CompareType = {
  SMALL: "SMALL",
  BIG: "BIG",
  SMALL_EQUAL: "SMALL_EQUAL",
  BIG_EQUAL: "BIG_EQUAL",
  DOES_NOT_CONTAIN: "DOES_NOT_CONTAIN",
  EQUAL: "EQUAL",
  NOT_EQUAL: "NOT_EQUAL",
};

export const interval = {
  SECOND_30: 30,
  SECOND_45: 45,
  MINUTE_1: 60,
  MINUTE_2: 120,
  MINUTE_3: 180,
  MINUTE_5: 300,
  MINUTE_10: 600,
  MINUTE_15: 900,
  MINUTE_30: 1200,
};
